"""reg_date to User

Revision ID: 80c9b555b9a1
Revises: 79b97818f712
Create Date: 2020-06-22 01:07:36.464490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c9b555b9a1'
down_revision = '79b97818f712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reg_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reg_date')
    # ### end Alembic commands ###
